/*
 * This file is automatically generated by Qt Design Studio.
 * Do not change.
*/

#include <QtQml/qqmlextensionplugin.h>

Q_IMPORT_QML_PLUGIN(contentPlugin)
Q_IMPORT_QML_PLUGIN(CA_Cockpik_IC_HMIPlugin)
Q_IMPORT_QML_PLUGIN(Quick3DAssets_TachMeterPlugin)
Q_IMPORT_QML_PLUGIN(Quick3DAssets_SpeedMeterPlugin)
Q_IMPORT_QML_PLUGIN(Quick3DAssets_Lane1Plugin)
Q_IMPORT_QML_PLUGIN(Quick3DAssets_LanePlugin)
Q_IMPORT_QML_PLUGIN(Quick3DAssets_EffectPlugin)
Q_IMPORT_QML_PLUGIN(Quick3DAssets_Car1Plugin)
Q_IMPORT_QML_PLUGIN(Quick3DAssets_CarPlugin)
Q_IMPORT_QML_PLUGIN(Quick3DAssets_BarPlugin)

